/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";

export const publicOrganisationRolesSchema = z.union([
  z.literal("manager"),
  z.literal("editor"),
  z.literal("client"),
  z.literal("agent"),
]);

//@ts-ignore
export const jsonSchema = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const graphqlPublicGraphqlArgsSchema = z.object({
  extensions: jsonSchema.optional(),
  operationName: z.string().optional(),
  query: z.string().optional(),
  variables: jsonSchema.optional(),
});

export const graphqlPublicGraphqlReturnsSchema = jsonSchema;

export const publicAgentAssignmentsRowSchema = z.object({
  active: z.boolean(),
  agent: z.string(),
  created_at: z.string(),
  dedicated_location: z.string(),
  id: z.string(),
  shifts: jsonSchema,
});

export const publicAgentAssignmentsInsertSchema = z.object({
  active: z.boolean().optional(),
  agent: z.string(),
  created_at: z.string().optional(),
  dedicated_location: z.string(),
  id: z.string().optional(),
  shifts: jsonSchema,
});

export const publicAgentAssignmentsUpdateSchema = z.object({
  active: z.boolean().optional(),
  agent: z.string().optional(),
  created_at: z.string().optional(),
  dedicated_location: z.string().optional(),
  id: z.string().optional(),
  shifts: jsonSchema.optional(),
});

export const publicAgentAssignmentsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("agent_assignments_agent_fkey"),
    columns: z.tuple([z.literal("agent")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organisation_branch_members"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("agent_assignments_dedicated_location_fkey"),
    columns: z.tuple([z.literal("dedicated_location")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("dedicated_locations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicDedicatedLocationsRowSchema = z.object({
  check_frequency: z.number(),
  client: z.string(),
  created_at: z.string(),
  id: z.string(),
  location: z.unknown(),
});

export const publicDedicatedLocationsInsertSchema = z.object({
  check_frequency: z.number().optional(),
  client: z.string().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  location: z.unknown(),
});

export const publicDedicatedLocationsUpdateSchema = z.object({
  check_frequency: z.number().optional(),
  client: z.string().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  location: z.unknown().optional(),
});

export const publicDedicatedLocationsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("dedicated_locations_client_fkey"),
    columns: z.tuple([z.literal("client")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organisation_branch_members"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicOrganisationBranchMembersRowSchema = z.object({
  branch: z.string(),
  created_at: z.string(),
  id: z.string(),
  metadata: jsonSchema.nullable(),
  role: publicOrganisationRolesSchema,
  user: z.string(),
});

export const publicOrganisationBranchMembersInsertSchema = z.object({
  branch: z.string(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  metadata: jsonSchema.optional().nullable(),
  role: publicOrganisationRolesSchema,
  user: z.string(),
});

export const publicOrganisationBranchMembersUpdateSchema = z.object({
  branch: z.string().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  metadata: jsonSchema.optional().nullable(),
  role: publicOrganisationRolesSchema.optional(),
  user: z.string().optional(),
});

export const publicOrganisationBranchMembersRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("organisation_branch_members_branch_fkey"),
    columns: z.tuple([z.literal("branch")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organisation_branches"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("organisation_branch_members_user_fkey"),
    columns: z.tuple([z.literal("user")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicOrganisationBranchesRowSchema = z.object({
  created_at: z.string(),
  id: z.string(),
  name: z.string(),
  organisation: z.string(),
});

export const publicOrganisationBranchesInsertSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  name: z.string(),
  organisation: z.string(),
});

export const publicOrganisationBranchesUpdateSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  name: z.string().optional(),
  organisation: z.string().optional(),
});

export const publicOrganisationBranchesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("organisation_branches_organisation_fkey"),
    columns: z.tuple([z.literal("organisation")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organisations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicOrganisationsRowSchema = z.object({
  admin: z.string(),
  created_at: z.string(),
  id: z.string(),
  name: z.string(),
});

export const publicOrganisationsInsertSchema = z.object({
  admin: z.string(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  name: z.string(),
});

export const publicOrganisationsUpdateSchema = z.object({
  admin: z.string().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  name: z.string().optional(),
});

export const publicUsersRowSchema = z.object({
  accepted_terms: z.boolean(),
  created_at: z.string(),
  device_fcm_ids: z.array(z.string()).nullable(),
  email: z.string(),
  emergency_phone: z.number().nullable(),
  home_address: z.string().nullable(),
  id: z.string(),
  name: z.string(),
  phone: z.number(),
  profile_picture: z.string().nullable(),
});

export const publicUsersInsertSchema = z.object({
  accepted_terms: z.boolean(),
  created_at: z.string().optional(),
  device_fcm_ids: z.array(z.string()).optional().nullable(),
  email: z.string(),
  emergency_phone: z.number().optional().nullable(),
  home_address: z.string().optional().nullable(),
  id: z.string(),
  name: z.string(),
  phone: z.number(),
  profile_picture: z.string().optional().nullable(),
});

export const publicUsersUpdateSchema = z.object({
  accepted_terms: z.boolean().optional(),
  created_at: z.string().optional(),
  device_fcm_ids: z.array(z.string()).optional().nullable(),
  email: z.string().optional(),
  emergency_phone: z.number().optional().nullable(),
  home_address: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string().optional(),
  phone: z.number().optional(),
  profile_picture: z.string().optional().nullable(),
});

export type PublicOrganisationRoles = z.infer<
  typeof publicOrganisationRolesSchema
>;
export type Json = z.infer<typeof jsonSchema>;
export type GraphqlPublicGraphqlArgs = z.infer<
  typeof graphqlPublicGraphqlArgsSchema
>;
export type GraphqlPublicGraphqlReturns = z.infer<
  typeof graphqlPublicGraphqlReturnsSchema
>;
export type PublicAgentAssignmentsRow = z.infer<
  typeof publicAgentAssignmentsRowSchema
>;
export type PublicAgentAssignmentsInsert = z.infer<
  typeof publicAgentAssignmentsInsertSchema
>;
export type PublicAgentAssignmentsUpdate = z.infer<
  typeof publicAgentAssignmentsUpdateSchema
>;
export type PublicAgentAssignmentsRelationships = z.infer<
  typeof publicAgentAssignmentsRelationshipsSchema
>;
export type PublicDedicatedLocationsRow = z.infer<
  typeof publicDedicatedLocationsRowSchema
>;
export type PublicDedicatedLocationsInsert = z.infer<
  typeof publicDedicatedLocationsInsertSchema
>;
export type PublicDedicatedLocationsUpdate = z.infer<
  typeof publicDedicatedLocationsUpdateSchema
>;
export type PublicDedicatedLocationsRelationships = z.infer<
  typeof publicDedicatedLocationsRelationshipsSchema
>;
export type PublicOrganisationBranchMembersRow = z.infer<
  typeof publicOrganisationBranchMembersRowSchema
>;
export type PublicOrganisationBranchMembersInsert = z.infer<
  typeof publicOrganisationBranchMembersInsertSchema
>;
export type PublicOrganisationBranchMembersUpdate = z.infer<
  typeof publicOrganisationBranchMembersUpdateSchema
>;
export type PublicOrganisationBranchMembersRelationships = z.infer<
  typeof publicOrganisationBranchMembersRelationshipsSchema
>;
export type PublicOrganisationBranchesRow = z.infer<
  typeof publicOrganisationBranchesRowSchema
>;
export type PublicOrganisationBranchesInsert = z.infer<
  typeof publicOrganisationBranchesInsertSchema
>;
export type PublicOrganisationBranchesUpdate = z.infer<
  typeof publicOrganisationBranchesUpdateSchema
>;
export type PublicOrganisationBranchesRelationships = z.infer<
  typeof publicOrganisationBranchesRelationshipsSchema
>;
export type PublicOrganisationsRow = z.infer<
  typeof publicOrganisationsRowSchema
>;
export type PublicOrganisationsInsert = z.infer<
  typeof publicOrganisationsInsertSchema
>;
export type PublicOrganisationsUpdate = z.infer<
  typeof publicOrganisationsUpdateSchema
>;
export type PublicUsersRow = z.infer<typeof publicUsersRowSchema>;
export type PublicUsersInsert = z.infer<typeof publicUsersInsertSchema>;
export type PublicUsersUpdate = z.infer<typeof publicUsersUpdateSchema>;
